---
exp_name: baseCNN # 0417
exp_dir: ../exp
device: 7 # 'mps' in M1 Mac
seed: None # If you want to reproduce set the seed
model_name: base_cnn # 
train_resume: False

dataset:
    scaler_type: std # std, invariant, norm, norm1, median

train:
    optimizer: Adam
    epoch: 50
    loss_type: multi_class # Or binary
    lr: 1.0e-3
    wd: 0.0e-4 # Adam
    momentum: 0.9 # SGD
    batch_size : 256

model: